platformName=Android
automationName=UiAutomator2
deviceName=emulator-5554
appPath=C:\\Users\\Daiana\\Downloads\\mobile\\testmobile2\\mda-2.0.2-23.apk
appPackage=com.saucelabs.mydemoapp.android
appActivity=com.saucelabs.mydemoapp.android.view.activities.SplashActivity
hub=http://localhost:4723
implicitWait=10